FROM odoo:14

COPY --chown=odoo addons /mnt/extra-addons
COPY --chown=odoo theme /mnt/theme
COPY --chown=odoo partner-contact /mnt/partner-contact
COPY --chown=odoo simplify_mops /mnt/simplify_mops
COPY --chown=odoo product-variant /mnt/product-variant
