apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commercecore-odoo-pvc
  namespace: commercecore
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
