apiVersion: v1
kind: Service
metadata:
  name: commercecore-odoo-svc
  namespace: commercecore
spec:
  ports:
  - protocol: TCP
    port: 8069
    targetPort: 8069
  selector:
    app: commercecore-odoo
  type: ClusterIP
