apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: python-volumes-clusterrole-binding
  # namespace: longhorn-system # Replace with your target namespace
subjects:
- kind: ServiceAccount
  name: python-volumes-service-account
  namespace: longhorn-system # Replace with your target namespace
roleRef:
  kind: ClusterRole
  name: python-volumes-clusterrole
  apiGroup: rbac.authorization.k8s.io
