apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v18e-ha-pvc
  namespace: v18e-ha
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
