apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iooluce-tls
  namespace: tyroled
spec:
  dnsNames:
  - iooluce.simplify-erp.de
  secretName: iooluce-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
