apiVersion: apps/v1
kind: Deployment
metadata:
  name: kj-odoo
  namespace: kj
  labels:
    app: kj-odoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kj-odoo
  template:
    metadata:
      labels:
        app: kj-odoo
    spec:
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: kj-odoo-pvc
      - name: odoo-config
        configMap:
          name: kj-odoo-config-app
      containers:
      - name: odoo
        image: crepo.re-cloud.io/re-cloud/odoo-kj:commit-1
        envFrom:
        - configMapRef:
            name: kj-odoo-config-db
        resources: {}
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
        - name: odoo-config
          mountPath: /etc/odoo

        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: harbor-re-cloud
      nodeSelector:
        odoo: "true"
      tolerations:
      - key: "odoo"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
