apiVersion: apps/v1
kind: Deployment
metadata:
  name: v18e-ha-postgre
  namespace: v18e-ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v18e-ha-postgre
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: v18e-ha-postgre
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-config
        image: postgres:17
        imagePullPolicy: IfNotPresent
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgresdb
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: v18e-ha-postgresql-pvc
