apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v18e-ha-postgresql-pvc
  namespace: v18e-ha
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
