apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kj-odoo-pvc
  namespace: kj
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
