apiVersion: v1
kind: ConfigMap
metadata:
  name: solarkraft-test-odoo-config-app
  namespace: solarkraft-test
  labels:
    app: solarkraft-test-odoo-config-app
data:
  odoo.conf: |
    [options]
    admin_passwd = 4i4ur9hb6p8mrse!
    list_db = False
    longpolling_port = 8072
    xmlrpc_port = 8069
    logfile=/var/log/odoo/odoo-server.log
    data_dir=/var/lib/odoo/odoo-data
    proxy_mode = True
    limit_time_cpu = 600
    limit_time_real = 1200
    limit_request = 8192
    max_cron_threads = 2
    workers = 5
    log_level = debug_sql
    #HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
    # Database Settings
    #HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

    #-----------------------------------------------------------------------------
    # Specify the database host (default localhost).
    #-----------------------------------------------------------------------------
    db_host = db-solarkraft-test

    #-----------------------------------------------------------------------------
    # Specify the database port (default None).
    #-----------------------------------------------------------------------------
    db_port = 5432

    #-----------------------------------------------------------------------------
    # Specify the database user name (default None).
    #-----------------------------------------------------------------------------
    db_user = odoo

    #-----------------------------------------------------------------------------
    # Specify the database password for db_user (default None) 
    #-----------------------------------------------------------------------------
    db_password = odoo



    addons_path= /mnt/extra-addons,/mnt/oca_collection/odoo-formio/,/mnt/oca_collection/helpdesk/,/mnt/oca_collection/server-brand/,/mnt/oca_collection/server-ux/,/mnt/extra-addons/custom_solarkraft,/mnt/extra-addons/llm

    # Configurations for DokuScan
    gg_project_id = simplify-erp-com
    gg_location = eu
    gg_processor_id = 40576c6a49a36f61
    gg_mime_type = application/pdf
    gg_default_auth_path = /mnt/extra-addons/poweron_ocr/simplify-erp-com-e319076613d7.json   
