apiVersion: v1
kind: Service
metadata:
  name: kj-postgre
  namespace: kj
  labels:
    app: kj-postgre
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: kj-postgre
  type: ClusterIP
