apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commercecore-postgresql-pvc
  namespace: commercecore
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
