apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kj-postgresql-pvc
  namespace: kj
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
