apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: innpro-repair-odoo-pvc
  namespace: innpro-repair
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
